thread = 8
--logger = "../log.txt" 
logger = nil 
harbor = 0
start = "main"
bootstrap = "snlua bootstrap"	-- The service for bootstrap
luaservice = "./service/?.lua;../server/?.lua;./examples/login/?.lua;"
lualoader = "lualib/loader.lua"
cpath = "./cservice/?.so;../luaclib/?.so;"
preload = '../server/preload.lua'
websocket_port = 8008
simpleweb_port = 8800
--daemon="../skynet.pid"
